export const Symbols = {
  PriceRepository: Symbol.for('PriceRepository'),
  WalletFactory: Symbol.for('Factory<IWalletService>'),
  EventAggregator: Symbol.for('EventAggregator'),
  Api: Symbol.for('Api'),
  GasPriceProvider: Symbol.for('GasPriceProvider'),
  DappStakingService: Symbol.for('DappStakingService'),
  DappStakingRepository: Symbol.for('DappStakingRepository'),
  MetadataRepository: Symbol.for('MetadataRepository'),
  SystemRepository: Symbol.for('SystemRepository'),
  EthCallRepository: Symbol.for('EthCallRepository'),
  XcmRepository: Symbol.for('XcmRepository'),
  XcmService: Symbol.for('XcmService'),
  BalanceFormatterService: Symbol.for('BalanceFormatterService'),
};
