name: Broken Links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'  # Trigger the workflow every month

jobs:
  build_and_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: yarn && yarn build

      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.7.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          args: --verbose "./src/modules/information/faq/dapp-staking/index.ts" "./src/modules/information/faq/transfer/index.ts" "./src/modules/information/faq/xvm-transfer/index.ts" "./src/data/ads.json" "./src/data/dynamic_links.json"

      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
