name: Deploy to Production
'on':
  workflow_dispatch:
    inputs:
      ref:
        description: 'Release Tag or branch'
        required: true
        default: 'v0.0.1'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ github.event.inputs.ref }}'