on:
  schedule:
    - cron: "*/15 * * * *"
name: Firestore backup
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: lfdm/firestore-backup-gh-action
        with:
          gcloudAuth: ${{ secrets.FIREBASE_BACKUP_GCLOUD_AUTH }}
          projectId: ${{ secrets.gcloud_project_id }}
          storageBucket: gs://astarnetwork-a4924.appspot.com
          collectionIds: 
