name: Firestore backup

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Firestore backup
        uses: lfdm/firestore-backup-gh-action@v1
        with:
          gcloudAuth: ${{ secrets.FIREBASE_BACKUP_GCLOUD_AUTH }}
          projectId: ${{ secrets.gcloud_project_id }}
          storageBucket: gs://astarnetwork-a4924.appspot.com
          collectionIds: "*"
