name: Firestore backup

on:
  schedule:
    - cron: "0 1 * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.FIREBASE_BACKUP_GCLOUD_AUTH }}
        export_default_credentials: true
    - run: gcloud info
    - run: gcloud config set project ${{ secrets.gcloud_project_id }}
    - run: gcloud firestore export gs://astar-apps-bkp
